spring:
  kafka:
    bootstrap-servers: localhost:9092 # Kafka cluster address
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest # Start reading at the earliest message
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true # Enable automatic offset commits
      auto-commit-interval: 100ms # Interval between two consecutive offset commits
    # Additional global properties
    properties:
      security.protocol: PLAINTEXT # Adjust this based on your Kafka cluster's security setup (e.g., SASL_SSL for secured clusters)
      # Other global properties can be added here
